[versions]
agp = "8.3.0"
kotlin = "2.0.0"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.7.0"
composeBom = "2023.08.00"
qrcodegen = "1.8.0"
base45 = "0.0.3"
mockk = "1.13.10"
cbor = "0.9"
zxing = "3.5.3"
json = "20140107"
ztzip = "1.17"
dokka = "1.9.20"
cose = "1.1.0"
json-parser = "1.1.1"
eddsa = "0.3.0"
bouncyCastle = "1.70"
codec = "1.15"
upokecenterCbor = "4.5.2"



[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
qrcodegen = { group = "io.nayuki", name = "qrcodegen", version.ref = "qrcodegen" }
base45 = { group = "io.github.ehn-digital-green-development", name = "base45", version.ref = "base45" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
cbor = { group = "co.nstant.in", name = "cbor", version.ref = "cbor" }
zxing = { group = "com.google.zxing", name = "core", version.ref="zxing" }
json = { group = "org.json", name = "json", version.ref = "json" }
ztzip = { group = "org.zeroturnaround", name = "zt-zip", version.ref = "ztzip" }
jsonparser = { group = "com.googlecode.json-simple", name = "json-simple", version.ref = "json-parser" }
commonCodec = { group = "commons-codec", name = "commons-codec", version.ref = "codec" }
eddsa = { group = "net.i2p.crypto", name = "eddsa", version.ref = "eddsa" }
bouncyCastle = { group = "org.bouncycastle", name = "bcprov-jdk15on", version.ref = "bouncyCastle" }
upokecenterCbor = { group = "com.upokecenter", name = "cbor", version.ref = "upokecenterCbor" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }